const IngredientsType = {
    ADD_INGRIEDIENT: "ADD_INGRIEDIENT",
    REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
    ADD_INGRIEDIENT_ALL: "ADD_INGRIEDIENT_ALL",
    REMOVE_INGREDIENT_ALL: "REMOVE_INGREDIENT_ALL"
}

export default IngredientsType